### ISSUE TITLE
Synsation_charger sample crashes on 'maintenance performed' events

### ISSUE THREAD

**Issue by JAG-UK** [jitsuin-inc/archivist-samples#15]
**Describe the bug**
synsation_charger sample crashes and fails to register RKVST Events on 'Maintenance Performed' event

**To Reproduce**
1. Run the synsation_charger sample for long enough to trigger the maintenance loop - this means running for long enough for at least one charging station to go over 1,000 units usage. I used: `${SYNSATION_CHARGER} -s 20200319 -S 20210318 -f 9876 -p ORD`
2. Wait and watch the trace

**Expected behavior**
The sample should register regular Maintenance Request / Maintenance Performed pairs.

**Additional context**
Here's the trace:
```
!! Agent responding to service request on ORD-ORD-0
Exception in thread Thread-41:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/api/archivist_samples/synsation/maintenance_worker.py", line 56, in threadmain
    service_device(charger, job_id, timewarp)
  File "/home/api/archivist_samples/synsation/maintenance_worker.py", line 38, in service_device
    charger.archivist_identity,
AttributeError: 'EVDevice' object has no attribute 'archivist_identity'
```

**Comment by JAG-UK** [comment]
This was fixed with #16. Closing.
